Update oracle_a_q_connection_factory.rb
1. Full Qualified name causes a Java exception : 
   oracle_a_q_connection_factory.rb:37:in `create_connection': undefined local variable or method `oracle' for #<JMS::OracleAQConnectionFactory:0xd0d407> (NameError)

2. Since username and password are not assigned (see lib/jms/connection.rb:200)
   and connection_factory.create_connection expects 2 arguments when username is not null ...
   We make the connection_factory.create_connection method supporting the two calls.